### ISSUE TITLE
[Request] Expose AWS --endpoint-url parameter for lupload

### ISSUE THREAD

**Issue by zachschultz** [QuiNovas/lambda-setuptools#22]
First of all, thank you for creating this project! 

Exposing `--endpoint-url` off of `boto` would be extremely useful for me, as I do local testing through [AWS Localstack](https://github.com/localstack/localstack). As part of the CI/CD pipeline I'm building, it'd be nice if I was able to parameterize my call to `lupload` with the endpoint url of AWS Localstack, instead of my production AWS instance.

I'm not sure how to request a feature so I'm opening an issue, if there's a better way please let me know.

**Comment by joseph-wortmann** [comment]
You're very welcome, I'm glad you find it so useful!

Yes, I can (most) probably add that parameter to lupload in the next few days. Looks pretty trivial.

**Comment by joseph-wortmann** [comment]
@zachschultz - I'm sorry that this has taken me so long. Honestly, I just forgot about it. I'm doing it today.

**Comment by joseph-wortmann** [comment]
@zachschultz there is a new version (0.2.2) in pypi that has the endpoint url available. Please let me know if this fixes your issue
