### ISSUE TITLE
Display error details when pip returns unsuccessfully 

### ISSUE THREAD

**Issue by fxbonnet** [QuiNovas/lambda-setuptools#26]
In ldist.py when the pip command fails (line 164) it only displays message "pip returned unsuccessfully"
It would be helpful when pip return code is not 0 to directly show the details. What about something like this:

```
stdout, stderr = pip.communicate()

if pip.returncode is not 0:
    log.info("pip stdout: {}".format(stdout))
    log.error("pip stderr: {}".format(stderr))
    raise DistutilsPlatformError('pip returned unsuccessfully')
else:
    log.debug("pip stdout: {}".format(stdout))
    log.debug("pip stderr: {}".format(stderr))
```

**Comment by joseph-wortmann** [comment]
I agree. Feel like creating a PR?

**Comment by joseph-wortmann** [comment]
Released to pypi. New version incorporating changes is 0.3.0. Thanks for the help!
