### ISSUE TITLE
python setup.py lupdate not working - unrecognised options

### ISSUE THREAD

**Issue by benjhastings** [QuiNovas/lambda-setuptools#30]
When I try and update a lambda function using the below command:
```
python setup.py lupdate --function-names=<my-function-name> --s3-bucket=<my-bucket-name> --access-key=<my-access-key> --secret-access-key=<my-secret-key>
```
I get the following error:
`error: option --s3-bucket not recognized`

I'm guessing this is because the `user_options` on `lupdate#LUpdate` do not accept the s3-bucket, aws-access-key or secret-access-key options.

I'm happy to put a PR in that resolves this issue.  Just wanted to make sure first that I wasn't causing the error myself by using incorrect syntax.

**Comment by joseph-wortmann** [comment]
It's because `lupdate` does not take `--s3-bucket` as an option. You must tell it that you want to `lupload` first (you can specify both), with takes the `--s3-bucket` option.

**Comment by benjhastings** [comment]
Ahh I didn't realise that I could chain `setup.py` arguments.  That worked perfectly - thanks for the quick response.

For anyone else finding this issue, the syntax I used to update an existing lambda function was:
```
python setup.py lupload --function-names=<my-function-name> --s3-bucket=<my-bucket-name> --access-key=<my-access-key> --secret-access-key=<my-secret-key> lupdate --function-names=<my-function-name> --region=<my-region>

```
