### ISSUE TITLE
[Feature Request] Support excluding files from the build

### ISSUE THREAD

**Issue by jacobeatsspam** [QuiNovas/lambda-setuptools#37]
When working in a development context, the current build implementation will pull in files like `__pycache__` and `.DS_Store` that I would like to exclude.

**Comment by joseph-wortmann** [comment]
OK. Make the changes that you desire to the build and create a PR.

**Comment by jacobeatsspam** [comment]
I might end up taking a different approach and making a different project. Thanks for your great work here though!

**Comment by jacobeatsspam** [comment]
Yeah, I'm making a different project instead.
