### ISSUE TITLE
pypandoc missing in requires

### ISSUE THREAD

**Issue by wonko21** [QuiNovas/lambda-setuptools#5]
Hi,

i am using your tool in a ci environment. I running into:

```
File "/tmp/easy_install-akkkxt1_/lambda-setuptools-0.1.7/setup.py", line 1, in <module>
   
ModuleNotFoundError: No module named 'pypandoc'
```
Apparently the `setup_requires=['pypandoc']`, is not daisy chained when I do a `setup_requires=['lambda_setuptools']`

Maybe it needs to be in `install_requires`?

cheers
w

**Comment by joseph-wortmann** [comment]
pypandoc is only used to build lambda-setuptools. Normally, you shouldn't have to do this - you should just have to "pip install lambda-setuptools", as this project has been listed and uploaded into PyPi. In fact, you should only have to do the pip install if your setup.py is not pulling the setup_requires from PyPi...

**Comment by joseph-wortmann** [comment]
the registry in PyPI - https://pypi.python.org/pypi/lambda-setuptools/0.1.7

**Comment by wonko21** [comment]
The problem seems to be related to me specifying `setup_requires=['lambda_setuptools']` 

Then just do a `python3 setup.py test`  expecting for setuptools to sort out missing dependencies. While doing that it seems your setup.py ist loaded and fails with the missing pypandoc.

When I do a pip3 install lambda_setuptools beforehand it works.
